### ISSUE TITLE
pasting formed '<ERuntimeMeshVertexTangentBasisType', an invalid preprocessing token

### ISSUE THREAD

**Issue by thescratt** [Koderz/RuntimeMeshComponent#80]
`RuntimeMeshGenericVertex.h:716:1: error: pasting formed '<ERuntimeMeshVertexTangentBasisType', an invalid preprocessing token`

Seeing this when attempting to build on macOS with 4.18.3

I am working my way through the MACRO magic to see if I can figure out the issue. But my head hurts a bit! :p

`In file included from ../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshComponent.h:8:
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:716:1: error: pasting formed '<ERuntimeMeshVertexTangentBasisType', an invalid preprocessing token
__DECLARE_RUNTIME_MESH_VERTEXINTERNAL(FRuntimeMeshVertexSimple, true, true, true, true, 1, ERuntimeMeshVertexTangentBasisType::Default, ERuntimeMeshVertexUVType::HighPrecision, RUNTIMEMESHCOMPONENT_API)
^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:646:3: note: expanded from macro '__DECLARE_RUNTIME_MESH_VERTEXINTERNAL'
                RUNTIMEMESH_VERTEX_DECLARE_NORMAL(NeedsNormal, TangentsType)                                                                                                                                                                                                                                                            \
                ^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:298:67: note: expanded from macro 'RUNTIMEMESH_VERTEX_DECLARE_NORMAL'
#define RUNTIMEMESH_VERTEX_DECLARE_NORMAL(HasNormal, TangentType) RUNTIMEMESH_VERTEX_DECLARE_NORMAL_##HasNormal(TangentType)
                                                                  ^
<scratch space>:41:1: note: expanded from here
RUNTIMEMESH_VERTEX_DECLARE_NORMAL_true
^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:296:99: note: expanded from macro 'RUNTIMEMESH_VERTEX_DECLARE_NORMAL_true'
#define RUNTIMEMESH_VERTEX_DECLARE_NORMAL_true(TangentType) FRuntimeMeshVertexTangentTypeSelector<##TangentType>::TangentsType Normal;
                                                                                                  ^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:716:1: error: pasting formed '<ERuntimeMeshVertexTangentBasisType', an invalid preprocessing token
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:647:3: note: expanded from macro '__DECLARE_RUNTIME_MESH_VERTEXINTERNAL'
                RUNTIMEMESH_VERTEX_DECLARE_TANGENT(NeedsTangent, TangentsType)                                                                                                                                                                                                                                                          \
                ^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:303:69: note: expanded from macro 'RUNTIMEMESH_VERTEX_DECLARE_TANGENT'
#define RUNTIMEMESH_VERTEX_DECLARE_TANGENT(HasTangent, TangentType) RUNTIMEMESH_VERTEX_DECLARE_TANGENT_##HasTangent(TangentType)
                                                                    ^
<scratch space>:42:1: note: expanded from here
RUNTIMEMESH_VERTEX_DECLARE_TANGENT_true
^
../../../../../../Volumes/MacHD/Indie/Planet 4.18/Plugins/UE4RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshGenericVertex.h:301:100: note: expanded from macro 'RUNTIMEMESH_VERTEX_DECLARE_TANGENT_true'
#define RUNTIMEMESH_VERTEX_DECLARE_TANGENT_true(TangentType) FRuntimeMeshVertexTangentTypeSelector<##TangentType>::TangentsType Tangent;`

**Comment by Koderz** [comment]
Hey @thescratt 

I messaged you in discord as well.  I ran through the HTML5 compiler on my Windows machine which usually complains about the same things I see from MacOS. Don't have access to a Mac right now so can't verify it there but I saw this issue on the HTML5 compile and it should now be fixed!  Let me know if you have any more issues compiling!

-Koderz

**Comment by thescratt** [comment]
Thanks for the very quick fix!
Can confirm this fixes this for macOS : https://github.com/Koderz/RuntimeMeshComponent/commit/d3be9cf65341988a35284727c8fb031306c89752
